### ISSUE TITLE
Source and pip versions mismatch

### ISSUE THREAD

**Issue by carlosafonso** [rohitkhatri/youtube-python#1]
Hi,

I noticed that the version available via `pip` (1.0.12) is not the same as the one in this repository (latest commit appears to be 1.0.0). Is the updated source available somewhere else?

Thanks.

**Comment by rohitkhatri** [comment]
Hey @carlosafonso, sorry for the delay, I have updated the version.

**Comment by carlosafonso** [comment]
Thanks.
