### ISSUE TITLE
ImportError: cannot import name 'YouTube'

### ISSUE THREAD

**Issue by softmarshmallow** [rohitkhatri/youtube-python#3]
the package was installed.
can `import youtube`
can `from youtube import YouTubeException`
cannot `from youtube import YouTube`

> ImportError: cannot import name 'YouTube'

what should i do?

**Comment by rohitkhatri** [comment]
I'm sorry for the wrong instruction, I have updated the `README.md` for better clarity and you can try this

```python
from youtube import API, YouTubeException
api = API(api_key='')
```
This should work.
