### ISSUE TITLE
PyPi does not have api_key fix

### ISSUE THREAD

**Issue by 3lixy** [rohitkhatri/youtube-python#4]
The commit https://github.com/rohitkhatri/youtube-python/commit/3d296e7d91068f0f60470a602d0d16163e06b04c does not seem to have made its way to https://pypi.org/project/youtube-python/.

Please can you version bump and publish on Pypi please as the latest release on pypi looks to be this commit https://github.com/rohitkhatri/youtube-python/commit/992dac56365c1bb3cd8f51a377db2039855ce590 which is behind the above commit with the api key fix.

**Comment by rohitkhatri** [comment]
@3lixy Sure will do that within 24 hours, thanks for letting me know.

**Comment by snelson3** [comment]
This fix still hasn't made it's way to pypi

**Comment by rohitkhatri** [comment]
Issue fixed in version 1.0.13
